//
// Created by WART3K on 19.10.24.
//

#ifndef COOL17_STATUS_H
#define COOL17_STATUS_H

typedef enum {
    COOL_OK = 0,
    COOL_UNKNOWN,
    COOL_WRONG_INPUT_PARAMETER,
    COOL_NULL_POINTER_ERROR,
    COOL_OVERFLOW,
    COOL_FORMAT_ERROR,
    COOL_PRINT_FAILED,
    COOL_LOGGER_INIT_ERROR,
    COOL_LOGGER_LEVEL_ERROR,
    COOL_LOGGER_FORMAT_ERROR,
    COOL_NOT_IMPLEMENTED,
    COOL_NOT_ENOUGH_MEMORY,
    COOL_ALLOCATION_ERROR,
    COOL_UNKNOWN_ERROR
}cool_status_t;

#endif //COOL17_STATUS_H
